name: Snapshots

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs: { }

jobs:
  tests:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        runtime: [ docker, podman ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup docker (missing on MacOS)
        if: ${{ matrix.os == 'macos-latest' && matrix.runtime == 'docker' }}
        run: |
          brew install docker
      - name: Setup podman (missing on MacOS)
        if: ${{ matrix.os == 'macos-latest' && matrix.runtime == 'podman' }}
        run: |
          brew install podman
      - name: Maven
        run: ${{ matrix.runtime }} version
