name: Snapshots

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs: { }

jobs:
  tests:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        runtime: [ docker, podman ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Maven
        run: ${{ matrix.runtime }} version
