name: PR build container images

on: [ push ]

jobs:
  container-images:
    if: ${{ github.event_name != 'pull_request' && github.repository_owner != 'windup' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Build container image
        run: |
          mvn -U -B package --file pom.xml -DskipTests \
          -Ddocker.name.windup.web=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/windup-web-openshift:${{ steps.extract_branch.outputs.branch }} \
          -Ddocker.name.windup.web.executor=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/windup-web-openshift-messaging-executor:${{ steps.extract_branch.outputs.branch }}

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push images to registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/windup-web-openshift:${{ steps.extract_branch.outputs.branch }}       
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/windup-web-openshift-messaging-executor:${{ steps.extract_branch.outputs.branch }}
